export const countriesData = [
  {
    country_name: "AUSTRALIA",
    country_language: "ENGLISH",
    id: 4,
    value: "en",
    country_flag: "/assets/flags/AUSTRALIA.svg",
  },
  {
    country_name: "BRASIL",
    country_language: "português",
    country_language_optional: "EN",
    id: 27,
    value: "PT",
    country_flag: "/assets/flags/BRAZIL.svg",
  },
  {
    country_name: "България",
    country_language: "български",
    country_language_optional: "EN",
    id: 15,
    value: "BG",
    country_flag: "/assets/flags/BULGARIA.svg",
  },
  {
    country_name: "CANADA",
    country_language: "Français",
    country_language_optional: "EN",
    id: 3,
    value: "en",
    optionalValue: "FR",
    country_flag: "/assets/flags/CANADA.svg",
  },
  {
    country_name: "Česko",
    country_language: "Česky",
    country_language_optional: "EN",
    id: 16,
    value: "CZ",
    country_flag: "/assets/flags/CZECH REPUBLIC.svg",
  },
  {
    country_name: "中国大陆",
    country_language: "普通话",
    country_language_optional: "EN",
    id: 20,
    value: "CN",
    country_flag: "/assets/flags/CHINA.svg",
  },
  {
    country_name: "Danmark",
    country_language: "Dansk",
    country_language_optional: "EN",
    id: 12,
    value: "DK",
    country_flag: "/assets/flags/DENMARK.svg",
  },
  {
    country_name: "Deutschland",
    country_language: "Deutsch",
    country_language_optional: "EN",
    id: 6,
    value: "DE",
    country_flag: "/assets/flags/GERMANY.svg",
  },
  {
    country_name: "España",
    country_language: "Español",
    country_language_optional: "EN",
    id: 8,
    value: "ES",
    country_flag: "/assets/flags/SPAIN.svg",
  },
  {
    country_name: "FRANCE",
    country_language: "Français",
    country_language_optional: "EN",
    id: 7,
    value: "FR",
    country_flag: "/assets/flags/FRANCE.svg",
  },
  {
    country_name: "भारत",
    country_language: "हिंदी",
    country_language_optional: "EN",
    id: 26,
    value: "IN",
    country_flag: "/assets/flags/INDIA.svg",
  },
  {
    country_name: "ITALIA",
    country_language: "ITALIANO",
    country_language_optional: "EN",
    id: 5,
    value: "IT",
    country_flag: "/assets/flags/ITALY.svg",
  },
  {
    country_name: "日本",
    country_language: "日本語",
    country_language_optional: "EN",
    id: 22,
    value: "JP",
    country_flag: "/assets/flags/JAPAN.svg",
  },

  {
    country_name: "Nederland",
    country_language: "Nederlands",
    country_language_optional: "EN",
    id: 10,
    value: "NL",
    country_flag: "/assets/flags/NETHERLANDS.svg",
  },
  {
    country_name: "Norge",
    country_language: "Norsk",
    country_language_optional: "EN",
    id: 11,
    value: "NO",
    country_flag: "/assets/flags/NORWAY.svg",
  },
   {
    country_name: "پاکستان",
    country_language: "اردو",
    country_language_optional: "EN",
    id: 19,
    value: "PK",
    country_flag: "/assets/flags/PAKISTAN.svg",
  },
  {
    country_name: "Philippines",
    country_language: "Tagalog",
    country_language_optional: "EN",
    id: 25,
    value: "PH",
    country_flag: "/assets/flags/PHILIPPINES.svg",
  },

  {
    country_name: "Polska",
    country_language: "Polski",
    country_language_optional: "EN",
    id: 14,
    value: "PL",
    country_flag: "/assets/flags/POLAND.svg",
  },
  {
    country_name: "Portugal",
    country_language: "português",
    country_language_optional: "EN",
    id: 9,
    value: "PT",
    country_flag: "/assets/flags/PORTUGAL.svg",
  },
  {
    country_name: "РОССИЯ",
    country_language: "РУССКИЙ",
    country_language_optional: "EN",
    id: 21,
    value: "RU",
    country_flag: "/assets/flags/RUSSIA.svg",
  },
  {
    country_name: "대한민국",
    country_language: "한국어",
    country_language_optional: "EN",
    id: 23,
    value: "KP",
    country_flag: "/assets/flags/SOUTH KOREA.svg",
  },
  {
    country_name: "Sverige",
    country_language: "Svenska",
    country_language_optional: "EN",
    id: 13,
    value: "SE",
    country_flag: "/assets/flags/SWEDEN.svg",
  },
  {
    country_name: "ไทย",
    country_language: "แบบไทย",
    country_language_optional: "EN",
    id: 24,
    value: "TH",
    country_flag: "/assets/flags/THAILAND.svg",
  },
  {
    country_name: "Türkiye",
    country_language: "Türkçe",
    country_language_optional: "EN",
    id: 17,
    value: "TR",
    country_flag: "/assets/flags/TÜRKİYE.svg",
  },
  {
    country_name: "الإمارات العربية المتحدة",
    country_language: "العربية",
    country_language_optional: "EN",
    id: 18,
    value: "AE",
    country_flag: "/assets/flags/UNITED ARAB EMIRATES.svg",
  },
  {
    country_name: "UNITED KINGDOM",
    country_language: "ENGLISH",
    id: 1,
    value: "en",
    country_flag: "/assets/flags/UNITED KINGDOM.svg",
  },
  {
    country_name: "UNITED STATES",
    country_language: "ENGLISH",
    id: 2,
    value: "en",
    country_flag: "/assets/flags/UNITED STATES.svg",
  },
];