export const countriesData = [
  {
    country_name: "UNITED KINGDOM",
    country_language: "ENGLISH",
    id: 1,
    value: "en",
    country_flag: "/assets/flags/UNITEDKINGDOM.png",
  },
  {
    country_name: "UNITED STATES",
    country_language: "ENGLISH",
    id: 2,
    value: "en",
    country_flag: "/assets/flags/UNITEDSTATES.png",
  },
  { 
    country_name: "CANADA",
    country_language: "ENGLISH",
    country_language_optional: "Français",
    id: 3,
    value: "en",
    optionalValue: "FR",
    country_flag: "/assets/flags/CANADA.png",
  },
  {
    country_name: "AUSTRALIA",
    country_language: "ENGLISH",
    id: 4,
    value: "en",
    country_flag: "/assets/flags/AUSTRALIA.png",
  },
  {
    country_name: "ITALIA",
    country_language: "ITALIANO",
    id: 5,
    value: "IT",
    country_flag: "/assets/flags/ITALY.png",
  },
  {
    country_name: "Deutschland",
    country_language: "Deutsch",
    id: 6,
    value: "DE",
    country_flag: "/assets/flags/GERMANY.png",
  },
  {
    country_name: "FRANCE",
    country_language: "Français",
    id: 7,
    value: "FR",
    country_flag: "/assets/flags/FRANCE.png",
  },
  {
    country_name: "España",
    country_language: "Español",
    id: 8,
    value: "ES",
    country_flag: "/assets/flags/SPAIN.png",
  },
  {
    country_name: "Portugal",
    country_language: "português",
    id: 9,
    value: "PT",
    country_flag: "/assets/flags/PORTUGAL.png",
  },
  {
    country_name: "Nederland",
    country_language: "Nederlands",
    id: 10,
    value: "NL",
    country_flag: "/assets/flags/NETHERLANDS.png",
  },
  {
    country_name: "Norge",
    country_language: "Norsk",
    id: 11,
    value: "NO",
    country_flag: "/assets/flags/NORWAY.png",
  },
  {
    country_name: "Danmark",
    country_language: "Dansk",
    id: 12,
    value: "DK",
    country_flag: "/assets/flags/DENMARK.png",
  },
  {
    country_name: "Sverige",
    country_language: "Svenska",
    id: 13,
    value: "SE",
    country_flag: "/assets/flags/SWEDEN.png",
  },
  {
    country_name: "Polska",
    country_language: "Polski",
    id: 14,
    value: "PL",
    country_flag: "/assets/flags/POLAND.png",
  },
  {
    country_name: "България",
    country_language: "български",
    id: 15,
    value: "BG",
    country_flag: "/assets/flags/BULGARIA.png",
  },
  {
    country_name: "Česko",
    country_language: "Česky",
    id: 16,
    value: "CZ",
    country_flag: "/assets/flags/CZECHREPUBLIC.png",
  },
  {
    country_name: "Türkiye",
    country_language: "Türkçe",
    id: 17,
    value: "TR",
    country_flag: "/assets/flags/TÜRKİYE.png",
  },
  {
    country_name: "الإمارات العربية المتحدة",
    country_language: "العربية",
    id: 18,
    value: "AE",
    country_flag: "/assets/flags/UNITEDARABEMIRATES.png",
  },
  {
    country_name: "پاکستان",
    country_language: "اردو",
    id: 19,
    value: "PK",
    country_flag: "/assets/flags/PAKISTAN.png",
  },
  {
    country_name: "中国大陆",
    country_language: "普通话",
    id: 20,
    value: "CN",
    country_flag: "/assets/flags/CHINA.png",
  },
  {
    country_name: "РОССИЯ",
    country_language: "РУССКИЙ",
    id: 21,
    value: "RU",
    country_flag: "/assets/flags/RUSSIA.png",
  },
  {
    country_name: "日本",
    country_language: "日本語",
    id: 22,
    value: "JP",
    country_flag: "/assets/flags/JAPAN.png",
  },
  {
    country_name: "대한민국",
    country_language: "한국어",
    id: 23,
    value: "KP",
    country_flag: "/assets/flags/SOUTHKOREA.png",
  },
  {
    country_name: "ไทย",
    country_language: "แบบไทย",
    id: 24,
    value: "TH",
    country_flag: "/assets/flags/THAILAND.png",
  },
  {
    country_name: "Philippines",
    country_language: "Tagalog",
    id: 25,
    value: "PH",
    country_flag: "/assets/flags/PHILIPPINES.png",
  },
  {
    country_name: "भारत",
    country_language: "हिंदी",
    id: 26,
    value: "IN",
    country_flag: "/assets/flags/INDIA.png",
  },
  {
    country_name: "BRASIL",
    country_language: "português",
    id: 27,
    value: "PT",
    country_flag: "/assets/flags/BRAZIL.png",
  },
];